### PR TITLE
Update quick-start.md to avoid serialization error

### PR DESCRIPTION
**Pull request by DevHusariaSolutions**
In recent Qwik version (1.3.1) proposed change is working, previous one throws error, that translationData cannot be serialized.

### CODE REVIEW

**Comment by robisim74** [comment]
@DevHusariaSolutions Thanks a lot for this pr. Personally, however, I cannot recreate the serialization error: can you provide some information (versions, configurations, etc.) to verify the problem it solves?

**Comment by DevHusariaSolutions** [comment]
Package qwik-speak@0.19.0(@builder.io/qwik@1.3.1) and just followed current version of tutorial.

Some env specs:
Windows 11 Version 10.0.22631 Build 22631
Brave [Version 1.61.109 Chromium: 120.0.6099.144 (Official Build) (64-bit)]

Also some components cannot translate phrases (I see keys of translations instead values), so I guess package itself may be unstable and that's why reproducing may not work.

**Comment by robisim74** [comment]
I just tried on Windows and also in WSL [this starter](https://github.com/robisim74/qwik-speak/blob/main/docs/tutorial-routing.md) with Qwik latest configuration:

```
  "devDependencies": {
    "@builder.io/qwik": "^1.3.2",
    "@builder.io/qwik-city": "^1.3.2",
    "@types/eslint": "^8.44.8",
    "@types/node": "^20.10.3",
    "@typescript-eslint/eslint-plugin": "^6.13.2",
    "@typescript-eslint/parser": "^6.13.2",
    "eslint": "^8.55.0",
    "eslint-plugin-qwik": "^1.3.2",
    "prettier": "^3.1.0",
    "qwik-speak": "^0.19.0",
    "typescript": "^5.3.2",
    "undici": "^5.26.0",
    "vite": "^5.0.6",
    "vite-tsconfig-paths": "^4.2.1"
  }
```

No issues.

The unstable package seems strange to me: either it works or it doesn't.

**Comment by DevHusariaSolutions** [comment]
I've changed code to:
```
const translationData = import.meta.glob<Translation>('/src/locales/**/*.json')

const loadTranslation$: LoadTranslationFn = server$(
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  async (lang: string, _: string) => {
    const dataFn = translationData[`/src/locales/${lang}.json`] as (() => Promise<Translation>) | undefined

    if (!dataFn) throw new Error('Missing translation file for ' + lang)

    return await translationData[`/src/locales/${lang}.json`]()
  }
)
```
(I have en-US.json in src/locales for sure)

And since translationData is now outside server$ scope, I gets error:
```
[vite] Internal server error: Value cannot be serialized in _._auto_translationData./src/locales/en-US.json, because it's a function named "/src/locales/en-US.json". You might need to convert it to a QRL using $(fn):

const /src/locales/en-US.json = $(() => __vite_ssr_dynamic_import__("/src/locales/en-US.json"));
```

**Comment by robisim74** [comment]
Ok, so it has nothing to do with basic use: it's due to your customization.

Furthermore, the `asset` parameter is fundamental, because it receives the value of the `assets` and `runtimeAssets` passed during configuration, to load only the necessary files.

I suggest you a simpler solution:
```
const loadTranslation$: LoadTranslationFn = server$(async (lang: string, asset: string) => {
  const data = await translationData[`/i18n/${lang}/${asset}.json`]?.();
  if (!data) throw new Error('Missing translation file for ' + lang);
  return data;
});
```

**Comment by DevHusariaSolutions** [comment]
This "customisation" is nothing what should impact on how it works.
You think that "asset" argument is fundamental, but in scope of loadTranslation it's only used to define which json file read.
Reading file works fine, when I used "translationData" inside "server$", but error mentioned above throws when it's in place as guideline mentions.
Did You test this case after fresh install of dependencies? I have recent ones installed from scratch just few days ago, maybe You are still using some older dependency.

**Comment by robisim74** [comment]
See my comment above: https://github.com/robisim74/qwik-speak/pull/106#issuecomment-1875599768

The basic operation suggested in the doc works. `loadTranslation$` is a customizable QRL function, with which you can load the translation files in the way you prefer: https://github.com/robisim74/qwik-speak/blob/main/docs/translation-functions.md

I think this pr/discussion can be closed.

**Comment by DevHusariaSolutions** [comment]
I've added You to my repository with code without my customisation and still throwing error.

**Comment by robisim74** [comment]
In `root.tsx`, change:

```
import * as speakConfig from './speak-config'

export default component$(() => {
  useQwikSpeak(speakConfig)
```

to:
```
import { config, translationFn } from './speak-config'

export default component$(() => {
  useQwikSpeak({ config, translationFn })
```
and it will work. 

Furthermore, to avoid other similar problems, it is advisable to create a separate file for `loadTranslation$`: please see the docs: https://github.com/robisim74/qwik-speak/blob/main/docs/quick-start.md#configuration

**Comment by DevHusariaSolutions** [comment]
I see, it works now. Even nothing more was exported from this file, I guess bundled chunk container more stuff. Nice it works, I gonna test if another issue related with this package will be solved as well.
Thanks for this package, key feature in qwik ecosystem

**Pull request closed without merging**
